version: "3.3"
services:
  apache-nifi: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache-nifi
    ports:
      - "8443:8443"
    volumes: 
      - "./data:/opt/nifi/nifi-current/data-in"
      - "./scripts:/opt/nifi/nifi-current/scripts"
    networks:
      - mysql
      
networks:
  mysql:
    external: true
