USE sim_datasus;

DROP TABLE IF EXISTS DIAGNOSTICO;
DROP TABLE IF EXISTS tem_causas_secundarias_por;
DROP TABLE IF EXISTS PESSOA_FALECIDA;
DROP TABLE IF EXISTS INVESTIGACAO;
DROP TABLE IF EXISTS OBITO;
DROP TABLE IF EXISTS CID10;
